a = float(input())
b = float(input())
c = float(input())
ac = abs(c - a)
bc = abs(c - b)
summ = ac + bc
print("Длина отрезка AC =", ac)
print("Длина отрезка BC =", bc)
print("Сумма длин отрезков AC и BC =", summ)